#!/bin/sh

set -e # to exit as soon as there is an error

hollight_version=3.0.0 # for dependencies
hollight_commit=72b2b70 # 3.0.0
hol2dk_commit=15b042c
lambdapi_commit=c1cb2edf
ocaml_version=5.3.0
rocq_version=9.0.0

opam_version=2.3.0
dune_version=3.20.2
camlp5_version=8.03.06

hollight_file=Logic/make.ml
base=`basename $hollight_file .ml`
dump_simp_option=
lpfile=mappings.lp
vfiles=mappings.v
mkfile=
require='Stdlib.NArith.BinNat Stdlib.Reals.Reals mathcomp.classical.classical_sets mathcomp.classical.cardinality mathcomp.ssreflect.choice mathcomp.ssreflect.ssrbool MathComp_HOLLight_Real_With_N.mappings HOLLight_Logic_fole'
root_path=`awk -F'[":]' '/logpath/{print $3}' opam`
jobs='-j32'

# we prefix $lpfile, $vfiles and $mkfile with "../../"
lpfile=../../$lpfile
if test -n "$mkfile"; then mkfile=../../$mkfile; fi
for f in $vfiles; do files="$files ../../$f"; done
vfiles=$files

line() { echo '------------------------------------------------------------'; }

start() {
    line
    if test -f STAGE; then i=`head -n1 STAGE`; else i=1; fi
    echo STAGE $i: $* ...
}

mkdir -p tmp
cd tmp

#usage: checkout_commit url commit
checkout_commit() {
    d=`basename $1 .git`
    start install $d
    git clone $1
    cd $d
    git checkout $2
    cd ..
}

create_opam_switch() {
    start create opam switch
    opam switch create . $ocaml_version
}

install_hollight_deps() {
    start install HOL-Light dependencies
    opam install -y camlp5.$camlp5_version
    opam install -y --deps-only hol_light.$hollight_version
}

install_lambdapi() {
    checkout_commit https://github.com/Deducteam/lambdapi.git $lambdapi_commit
    cd lambdapi
    git checkout -b reproduce
    opam install -y .
    cd ..
}

install_rocq() {
    start install rocq
    opam install -y rocq-prover.$rocq_version
}

install_deps() {
    start install dependencies
    opam repo add rocq-released https://rocq-prover.org/opam/released
    opam install -y --deps-only ..
}

install_hol2dk() {
    checkout_commit https://github.com/Deducteam/hol2dk.git $hol2dk_commit
    cd hol2dk
    dune build && dune install
    cd ..
}

install_hollight() {
    checkout_commit https://github.com/jrh13/hol-light.git $hollight_commit
    cd hol-light
    make
    cd ..
}

patch_hollight() {
    start patch hol-light
    hol2dk patch
}

dump_proofs() {
    start dump hol-light proofs
    cd hol-light
    cp ../../$base.ml $hollight_file
    hol2dk dump-simp$dump_simp_option $hollight_file
    cd ..
}

config_output_dir() {
    start configure output directory
    mkdir -p output
    cd output
    if test -f Makefile; then make $jobs clean-all; fi
    hol2dk config $hollight_file $root_path $require $vfiles $mkfile $lpfile
    cd ..
}

translate_proofs() {
    start translate HOL-Light proofs to lambdapi and rocq
    cd output
    make split
    make $jobs lp
    make $jobs v
    make $jobs merge-spec-files
    make $jobs rm-empty-deps
    cd ..
}

check_proofs() {
    start check proofs
    cd output
    make $jobs vo
    cd ..
}

remove_empty_modules() {
    sed -e "s/${base}_//g" \
        -e "/^Require Import ${root_path}\.theory_hol\.$/d" \
        -e "/^Require Import ${root_path}\.types\.$/d" \
        -e "/^Require Import ${root_path}\.axioms\.$/d" \
        $1
}

create_and_check_opam_library() {
    start create opam library
    cd output
    make $jobs opam
    cd ..
    mkdir -p opam
    cd opam
    cp ../../opam ../../Makefile $vfiles $mkfile .
    remove_empty_modules ../output/${base}_terms.v > terms.v
    remove_empty_modules ../output/${base}_opam.v > theorems.v
    sed -i -e 's/NUMERAL //g' -e 's/(N0)/N0/g' terms.v theorems.v
    make $jobs
    cd ..
}

compare_opam_file() {
    line
    echo compare $1 ...
    diff ../$1 opam/$1
}

compare_opam_files() {
    for f in terms.v theorems.v
    do
        compare_opam_file $f
    done
}

export HOLLIGHT_DIR=`pwd`/hol-light
export HOL2DK_DIR=`pwd`/hol2dk

stage() {
    if test -f STAGE
    then
        i=`head -n1 STAGE`
        i=`expr $i + 1`
    else
        i=1
    fi
    if test $i -eq $1
    then
        $2
        echo $1 > STAGE
    fi
}

if test -n "$1"
then
    expr $1 - 1 > STAGE
fi

stage 1 create_opam_switch
eval `opam env`
stage 2 install_hollight_deps
stage 3 install_lambdapi
stage 4 install_rocq
stage 5 install_deps
stage 6 install_hol2dk
stage 7 install_hollight
stage 8 patch_hollight
stage 9 dump_proofs
stage 10 config_output_dir
stage 11 create_and_check_opam_library
stage 12 compare_opam_files
stage 13 translate_proofs
stage 14 check_proofs
